credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: "$2b$12$REPLACE_WITH_HASHED_PASSWORD"
    user2:
      email: user2@example.com
      name: User Two
      password: "$2b$12$REPLACE_WITH_HASHED_PASSWORD"

cookie:
  name: streamlit_auth_cookie
  key: random_signature_key_change_this
  expiry_days: 30
